### PR TITLE
Roughly translate into English

### PR DESCRIPTION
**Pull request by DavidMoritz**
DO NOT MERGE TO MASTER!
There weren't any other branches available to merge this into. I suggest you create a new branch called "feature/english" and merge it into that. Then, if someone wants the English version, you can tell them to pull from that feature branch.

### CODE REVIEW

**Comment by mgierw** [comment]
Well, I don't know how to do this. I created branch you mentioned, but affraid to merge your pull request because I don't know where it will be merged - to master or feature/english?... I added you to colaborators - maybe you'll be able to do this properly. Thx in advance.

**Comment by DavidMoritz** [comment]
Merging this to create feature branch for English

**Comment by DavidMoritz** [comment]
You can now safely merge this into the feature/english branch. I do not have merge permissions. This is a fantastic app! Thank you for making it!

**Comment by mgierw** [comment]
Done.

**Pull request merged**
