### PR TITLE
Revert "Give users the ability to set which services they want to use"

### PR DESCRIPTION
**Pull request by DavidMoritz**
Reverts mgierw/auto-foe#3

### CODE REVIEW

**Review by DavidMoritz — COMMENTED** [review]
I didn't mean to add the english to master

**Comment by DavidMoritz** [comment]
I need to apologize. I was trying to be so careful. It looks like my english commits made it into your master branch. I don't understand how it happened.
Please revert this merge to get master back
then only grab the following commits:
a95137f
0ed04f0
9fee1ea

**Comment by DavidMoritz** [comment]
Alternatively, you may decide to make a "feature/polish" branch and keep english in master for wider appeal.

**Comment by mgierw** [comment]
I think English should be in master.

**Pull request merged**
